/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/model/gltf/Wattson_Strange_Attractor.gltf 
*/
"use client";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Wsa = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./model/gltf/Wattson_Strange_Attractor.gltf"
  );
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    const firstAnimationName = names[0];

    if (firstAnimationName && actions[firstAnimationName]) {
      const firstAction = actions[firstAnimationName];
      firstAction.reset().fadeIn(0.5).play();

      // Cleanup when the component unmounts
      return () => {
        // Introduce a delay before stopping the animation
        setTimeout(() => {
          firstAction.stop();
        }, 100);
      };
    }
  }, []);
  return (
    <group
      ref={group}
      position={[0, 0, 0.006]}
      scale={50.54}
      {...props}
      dispose={null}
    >
      <group>
        <group name="Joints">
          <group name="jx_c_delta" rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <group name="jx_c_start" />
            <group name="jx_c_pov" position={[0, 0, 1]}>
              <group name="jx_c_camera" />
            </group>
            <primitive object={nodes.def_c_hip} />
          </group>
        </group>
        <group name="Wattson_Strange_Attractor" rotation={[Math.PI / 2, 0, 0]}>
          <skinnedMesh
            name="wattson_head_01"
            geometry={nodes.wattson_head_01.geometry}
            material={materials["Material #25"]}
            skeleton={nodes.wattson_head_01.skeleton}
          />
          <skinnedMesh
            name="wattson_head"
            geometry={nodes.wattson_head.geometry}
            material={materials["Material #26"]}
            skeleton={nodes.wattson_head.skeleton}
          />
          <skinnedMesh
            name="wattson_hands"
            geometry={nodes.wattson_hands.geometry}
            material={materials["Material #27"]}
            skeleton={nodes.wattson_hands.skeleton}
          />
          <skinnedMesh
            name="wattson_helmet"
            geometry={nodes.wattson_helmet.geometry}
            material={materials["Material #28"]}
            skeleton={nodes.wattson_helmet.skeleton}
          />
          <skinnedMesh
            name="wattson_backpack01"
            geometry={nodes.wattson_backpack01.geometry}
            material={materials["Material #30"]}
            skeleton={nodes.wattson_backpack01.skeleton}
          />
          <skinnedMesh
            name="wattson_jacket"
            geometry={nodes.wattson_jacket.geometry}
            material={materials["Material #32"]}
            skeleton={nodes.wattson_jacket.skeleton}
          />
          <skinnedMesh
            name="wattson_backpack"
            geometry={nodes.wattson_backpack.geometry}
            material={materials["Material #30"]}
            skeleton={nodes.wattson_backpack.skeleton}
          />
          <skinnedMesh
            name="wattson_body"
            geometry={nodes.wattson_body.geometry}
            material={materials["Material #31"]}
            skeleton={nodes.wattson_body.skeleton}
          />
        </group>
        <group name="Default_light" />
      </group>
    </group>
  );
};
export default Wsa;
useGLTF.preload("./model/gltf/Wattson_Strange_Attractor.gltf");
